/*
    1) give 5 best books of genre 'drama'
*/
SELECT TOP 5 BOOKS.TITLE FROM BOOKS
WHERE GENRE.NAME = 'drama'
INNER JOIN GENRE ON GENRE.ID = BOOKS.GENRE_ID
ORDER BY BOOKS.AVERAGE_RATING DESC


/*
    3) user that ranked the most books
*/
SELECT TOP 1 USERS.FULL_NAME
FROM USERS INNER JOIN RATINGS ON RATINGS.USER_ID = USERS.ID
GROUP BY USERS.FULL_NAME
ORDER BY COUNT(RATINGS.ID) DESC

/*
    5) the worst books written by author 'J.K.Rowling'
*/
SELECT TOP 1 BOOKS.TITLE FROM BOOKS
WHERE AUTHORS.FULL_NAME = 'J.K.Rowling'
INNER JOIN AUTHORS ON AUTHORS.ID = BOOKS.AUTHOR_ID
ORDER BY BOOKS.AVERAGE_RATING ASC

/*
    7) update book 'Harry Potter'
*/
UPDATE BOOKS
SET AVERAGE_RATING = 5, ORIGINAL_PUBLICATION_YEAR = 1990, LANGUAGE_CODE = 'ru'
WHERE TITLE = 'Harry Potter'


/*
    9) for each user select books with same language
       and that aren't older then 20 years
*/
SELECT USERS.FULL_NAME FROM USERS
GROUP BY USERS.FULL_NAME
WHERE USERS.LANGUAGE = (
    SELECT BOOKS.LANGUAGE_CODE FROM BOOKS
    WHERE BOOKS.ORIGINAL_PUBLICATION_YEAR >= 1999
)