
/*
DROP TABLE BOOKS_TAGS;
DROP TABLE BOOKS_AUTHORS;
DROP TABLE RATINGS;
DROP TABLE BOOKS;
DROP TABLE USERS;
DROP TABLE TAGS
DROP TABLE AUTHORS;
*/

CREATE TABLE AUTHORS
(
SK_IDAUTHOR INT PRIMARY KEY
, NAMEAUTHOR VARCHAR(200)
)

CREATE TABLE BOOKS
(
SK_IDBOOK INT PRIMARY KEY
, IDBOOK INT
, IDBESTBOOK INT
, IDWORK INT
, BOOKSCOUNT INT
, ISBN VARCHAR(16)
, YEAROFPUBLICATION INT
, ORIGINALTITLE VARCHAR(200)
, TITLE VARCHAR(200) 
, LANGUAGE VARCHAR(10)
, AVERAGERATING FLOAT
, RATINGSCOUNT INT
, WORKRATINGSCOUNT INT
, WORKTEXTREVIEWSCOUNT INT
)


CREATE TABLE BOOKS_AUTHORS
(
SK_IDAUTHOR INT NOT NULL,
SK_IDBOOK INT NOT NULL
)


CREATE TABLE USERS
(
SK_IDUSER INT PRIMARY KEY
, NAMEUSER VARCHAR(200)
, GENDER VARCHAR(25)
, NATIVELANGUAGE VARCHAR(10)
)


CREATE TABLE RATINGS
(
SK_IDUSER INT NOT NULL,
SK_IDBOOK INT NOT NULL,
RATING INT
)

CREATE TABLE TAGS
(
SK_IDTAG INT PRIMARY KEY
, NAMETAG VARCHAR(150)
)

CREATE TABLE BOOKS_TAGS
(
SK_IDTAG INT NOT NULL,
SK_IDBOOK INT NOT NULL,
COUNT INT
)

/*FOREIGN KEYS - EXECUTE AFTER DATA LOAD*/

ALTER TABLE RATINGS ADD FOREIGN KEY (SK_IDUSER) REFERENCES USERS(SK_IDUSER);
ALTER TABLE RATINGS ADD FOREIGN KEY (SK_IDBOOK) REFERENCES BOOKS(SK_IDBOOK);
ALTER TABLE RATINGS ADD PRIMARY KEY (SK_IDUSER,SK_IDBOOK);

ALTER TABLE BOOKS_AUTHORS ADD FOREIGN KEY (SK_IDAUTHOR) REFERENCES AUTHORS(SK_IDAUTHOR);
ALTER TABLE BOOKS_AUTHORS ADD FOREIGN KEY (SK_IDBOOK) REFERENCES BOOKS(SK_IDBOOK);
ALTER TABLE BOOKS_AUTHORS ADD PRIMARY KEY (SK_IDAUTHOR,SK_IDBOOK);

ALTER TABLE BOOKS_TAGS ADD FOREIGN KEY (SK_IDTAG) REFERENCES TAGS(SK_IDTAG);
ALTER TABLE BOOKS_TAGS ADD FOREIGN KEY (SK_IDBOOK) REFERENCES BOOKS(SK_IDBOOK);
ALTER TABLE BOOKS_TAGS ADD PRIMARY KEY (SK_IDTAG,SK_IDBOOK)

/*
DELETE FROM BOOKS_TAGS;
DELETE FROM BOOKS_AUTHORS;
DELETE FROM RATINGS;
DELETE FROM BOOKS;
DELETE FROM USERS;
DELETE FROM TAGS
DELETE FROM AUTHORS;
*/

